/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Calculator.java
 *
 * Created on Aug 10, 2016, 6:45:22 PM
 */

package javaapplication3;

/**
 *
 * @author Leo
 */
public class Calculator extends javax.swing.JFrame {

    /** Creates new form Calculator */
    public Calculator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calculatorScreen = new javax.swing.JTextField();
        numberOne16 = new javax.swing.JButton();
        numberOne15 = new javax.swing.JButton();
        numberOne14 = new javax.swing.JButton();
        numberOne13 = new javax.swing.JButton();
        numberOne7 = new javax.swing.JButton();
        numberOne8 = new javax.swing.JButton();
        numberOne5 = new javax.swing.JButton();
        numberOne6 = new javax.swing.JButton();
        numberOne11 = new javax.swing.JButton();
        numberOne = new javax.swing.JButton();
        numberOne9 = new javax.swing.JButton();
        numberOne10 = new javax.swing.JButton();
        numberOne1 = new javax.swing.JButton();
        numberOne2 = new javax.swing.JButton();
        numberOne4 = new javax.swing.JButton();
        numberOne3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculatorScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorScreenActionPerformed(evt);
            }
        });

        numberOne16.setText("=");
        numberOne16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne16ActionPerformed(evt);
            }
        });

        numberOne15.setText("-");
        numberOne15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne15ActionPerformed(evt);
            }
        });

        numberOne14.setText("*");
        numberOne14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne14ActionPerformed(evt);
            }
        });

        numberOne13.setText("/");
        numberOne13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne13ActionPerformed(evt);
            }
        });

        numberOne7.setText("0");
        numberOne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne7ActionPerformed(evt);
            }
        });

        numberOne8.setText(".");
        numberOne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne8ActionPerformed(evt);
            }
        });

        numberOne5.setText("6");
        numberOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne5ActionPerformed(evt);
            }
        });

        numberOne6.setText("1");
        numberOne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne6ActionPerformed(evt);
            }
        });

        numberOne11.setText("+");
        numberOne11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne11ActionPerformed(evt);
            }
        });

        numberOne.setText("9");
        numberOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneActionPerformed(evt);
            }
        });

        numberOne9.setText("2");
        numberOne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne9ActionPerformed(evt);
            }
        });

        numberOne10.setText("3");
        numberOne10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne10ActionPerformed(evt);
            }
        });

        numberOne1.setText("7");
        numberOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne1ActionPerformed(evt);
            }
        });

        numberOne2.setText("8");
        numberOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne2ActionPerformed(evt);
            }
        });

        numberOne4.setText("5");
        numberOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne4ActionPerformed(evt);
            }
        });

        numberOne3.setText("4");
        numberOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOne3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculatorScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numberOne7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numberOne6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numberOne3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(numberOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numberOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOne16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOne15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOne14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOne13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(calculatorScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOne3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOne6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOne7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOne16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneActionPerformed
        // TODO add your handling code here:
        this.calculatorScreen.setText("1");
        
    }//GEN-LAST:event_numberOneActionPerformed

    private void calculatorScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorScreenActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_calculatorScreenActionPerformed

    private void numberOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne1ActionPerformed

    private void numberOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne2ActionPerformed

    private void numberOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne3ActionPerformed

    private void numberOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne4ActionPerformed

    private void numberOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne5ActionPerformed

    private void numberOne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne6ActionPerformed

    private void numberOne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne7ActionPerformed

    private void numberOne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne8ActionPerformed

    private void numberOne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne9ActionPerformed

    private void numberOne10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne10ActionPerformed

    private void numberOne11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne11ActionPerformed

    private void numberOne13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne13ActionPerformed

    private void numberOne14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne14ActionPerformed

    private void numberOne15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne15ActionPerformed

    private void numberOne16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOne16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOne16ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calculatorScreen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton numberOne;
    private javax.swing.JButton numberOne1;
    private javax.swing.JButton numberOne10;
    private javax.swing.JButton numberOne11;
    private javax.swing.JButton numberOne13;
    private javax.swing.JButton numberOne14;
    private javax.swing.JButton numberOne15;
    private javax.swing.JButton numberOne16;
    private javax.swing.JButton numberOne2;
    private javax.swing.JButton numberOne3;
    private javax.swing.JButton numberOne4;
    private javax.swing.JButton numberOne5;
    private javax.swing.JButton numberOne6;
    private javax.swing.JButton numberOne7;
    private javax.swing.JButton numberOne8;
    private javax.swing.JButton numberOne9;
    // End of variables declaration//GEN-END:variables

}
